=== LuzRdgz/Basic_XML/ejercicio_2.dtd
<!ELEMENT Mensaje (Remite,Destinatario,Asunto,Texto)*>
<!ELEMENT Remite (Nombre,Email)*>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Destinatario (Nombre,Email)*>
<!ELEMENT Asunto (#PCDATA)>
<!ELEMENT Texto (Inicio,Desarrollo,Final)>
<!ELEMENT Inicio (#PCDATA)>
<!ELEMENT Desarrollo (#PCDATA)>
<!ELEMENT Final (#PCDATA)>

=== LuzRdgz/Basic_XML/ejercicio_2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Mensaje SYSTEM "ejercicio_2.dtd">
<Mensaje>
    <Remite>
        <Nombre>Alfredo Reino</Nombre>
        <Email>alf@ibium.com</Email>
    </Remite>
    <Destinatario>
        <Nombre>Bill Clinton</Nombre>
        <Email>president@whitehouse.gov</Email>
    </Destinatario>
    <Asunto>Hola Bill</Asunto>
    <Texto>
        <Inicio>¿Hola qué tal?</Inicio>
        <Desarrollo>
            Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto.
        </Desarrollo>
        <Final>Un saludo</Final>
    </Texto>
</Mensaje>
